CREATE DATABASE UserPlatformDB;

CREATE TABLE UserDetails (
	 UserId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID()
	,FirstName NVARCHAR(100) NOT NULL
	,MiddleName NVARCHAR(100)
	,LastName NVARCHAR(100)  NOT NULL
	,UserName NVARCHAR(100)  NOT NULL
	,MobileNo BIGINT  NOT NULL
	,Email NVARCHAR(255)  NOT NULL
	,Password NVARCHAR(255)  NOT NULL
	,CreatedOn DATETIME 
	,ModifiedOn DATETIME
	,IsLocked BIT DEfault 0
	)